# Generated by Django 5.0.4 on 2024-08-15 22:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social_media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='social_media')),
                ('link', models.CharField(max_length=500)),
                ('descrtion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Text_pic_wep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('based_pic', models.ImageField(upload_to='pic_wep')),
                ('logo', models.ImageField(upload_to='pic_wep')),
                ('about_us', models.TextField()),
                ('contect_us', models.TextField()),
                ('trademark', models.CharField(max_length=400)),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='sizesmodel',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sizesmodel',
            name='descrtions_size_fit',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_cart', to='app1.products'),
        ),
        migrations.AlterField(
            model_name='products',
            name='photo',
            field=models.FileField(upload_to='product_images/'),
        ),
        migrations.AlterField(
            model_name='sizesmodel',
            name='size',
            field=models.CharField(choices=[('small', 's'), ('medium', 'm'), ('large', 'l'), ('Xs', 'xs'), ('Xl', 'xl'), ('XXl', 'xxl')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app1.products')),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to='app1.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'product')},
            },
        ),
    ]
