# Generated by Django 5.0.4 on 2024-09-15 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_social_media_text_pic_wep_products_discount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='products',
            name='discount',
        ),
        migrations.AddField(
            model_name='products',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Featured on Homepage'),
        ),
        migrations.AddField(
            model_name='sender_email',
            name='pic_email',
            field=models.ImageField(blank=True, upload_to='email_images/'),
        ),
        migrations.AddField(
            model_name='text_pic_wep',
            name='about_us_pic',
            field=models.ImageField(blank=True, null=True, upload_to='pic_wep'),
        ),
        migrations.AddField(
            model_name='text_pic_wep',
            name='based_pic2',
            field=models.ImageField(blank=True, null=True, upload_to='pic_wep'),
        ),
        migrations.AddField(
            model_name='text_pic_wep',
            name='based_pic3',
            field=models.ImageField(blank=True, null=True, upload_to='pic_wep'),
        ),
        migrations.AddField(
            model_name='text_pic_wep',
            name='contect_us_pic',
            field=models.ImageField(blank=True, null=True, upload_to='pic_wep'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='color',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='size',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AlterField(
            model_name='products',
            name='sale_status',
            field=models.CharField(choices=[('sale', 'Sale'), ('sale_out', 'Sale Out'), ('sold_out', 'sold_out'), ('none', 'none')], default='sale', max_length=10),
        ),
        migrations.AlterField(
            model_name='social_media',
            name='descrtion',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='social_media',
            name='link',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='social_media',
            name='logo',
            field=models.ImageField(null=True, upload_to='social_media'),
        ),
        migrations.AlterField(
            model_name='social_media',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='text_pic_wep',
            name='about_us',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='text_pic_wep',
            name='based_pic',
            field=models.ImageField(blank=True, null=True, upload_to='pic_wep'),
        ),
        migrations.AlterField(
            model_name='text_pic_wep',
            name='contect_us',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='text_pic_wep',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='pic_wep'),
        ),
        migrations.AlterField(
            model_name='text_pic_wep',
            name='trademark',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='cartmodel',
            name='discount_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.discountcode'),
        ),
        migrations.AddField(
            model_name='products',
            name='Discount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
